blog/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views as BlogViews

app_name = 'blog'

urlpatterns = [
    path('', BlogViews.Index().index, name='Index'),
    path('tags/', BlogViews.Tags, name='Tags'),
    path('archives/', BlogViews.Archives, name='Archives'),
    path('about/', BlogViews.About, name='About'),
    path('project/', BlogViews.Project, name='Project'),


    path('tags/<tag>/', BlogViews.Index().tags, name='tags'),
    path('post/<int:pk>/',BlogViews.Detail.as_view(), name='post'),
    path('content.json/',BlogViews.search, name='search'),




]

django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('blog/', include('blog.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

urlpatterns += staticfiles_urlpatterns()  # 为了让gunicorn启动时收取到静态文件

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'django_blog.views.page_not_found'
handler500 = 'django_blog.views.server_error'

blog/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mdeditor.fields import MDTextField


# Create your models here.
class Tag(models.Model):
    '''
    文章标签,继承 model.Model
    '''
    name = models.CharField(max_length=100, unique=True, verbose_name=u'标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'标签'
        verbose_name_plural = u'标签'


class Post(models.Model):
    '''
    博客正文内容：继承 model.Model
    '''
    # 文章标题、目录与正文
    title = models.CharField(max_length=100, verbose_name=u'标题')
    body = MDTextField(verbose_name=u'正文')

    # 文章创建时间和最近更新时间
    created_time = models.DateTimeField(verbose_name=u'创建时间')
    modified_time = models.DateTimeField(auto_now=True, verbose_name=u'更新时间')

    # 文章标签：一篇文章可以有多个标签，一对多关系，可为空
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=u'标签')
    # 文章作者：一篇文章只有一个作者，与文章一对一关系
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u'作者')

    # 文章访问量
    views = models.PositiveIntegerField(default=0, verbose_name=u'阅读数')

    # 文章是否顶置，默认不顶置
    is_top = models.BooleanField(default=False, verbose_name=u'顶置文章')
    # 文章发布状态，默认是创建成功就发布
    is_show = models.BooleanField(default=True, verbose_name=u'发布状态')

    # 文章类型：注意 about 和 project 只能创建一个
    post_type = models.CharField(max_length=20,
                                 choices=(('post', u'博客文章'),
                                          ('about', u'关于页面'),
                                          ('project', u'我的项目'),
                                          ),
                                 default='post',
                                 verbose_name=u'类型'
                                 )

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    # 自定义 increase_views 方法：用于统计访问量
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        # 获取 Post 列表时，按照顶置、创建时间排序
        ordering = ['-is_top', '-created_time']
        verbose_name = u'博客文章'
        verbose_name_plural = u'博客文章'


# 友情链接
class Links(models.Model):
    name = models.CharField(max_length=100, verbose_name=u'站点名称')
    url = models.URLField(max_length=225, verbose_name=u'站点链接')
    is_show = models.BooleanField(default=True, verbose_name=u'是否展示')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'友情链接'
        verbose_name_plural = u'友情链接'

blog/views.py
# _*_ coding:utf-8 _*_

from django.shortcuts import render, get_object_or_404
from django.views import View
from blog.models import Post,Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db.models.aggregates import Count
import json,re
from django.http import HttpResponse
from django_blog.views import page_not_found
import markdown
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

def MD():
    return markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])

# 博客文章列表页面
class Index():
    def __init__(self):
        # 定义 per_page 的值，每个页面的文章数
        self.per_page = 5

    def index(self,request):
        # 博客首页：获取Post表中所有文章列表
        post_list = Post.objects.filter(is_show=True, post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list,page=page,request=request)


    def category(self,request, category):
        # 分类：按照标签(category)查询Post表中的文章列表
        post_list = Post.objects.filter(category__name=category,is_show=True,post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)

    def tags(self,request, tag):
        # 标签：按照标签(tag)查询Post表中的文章列表
        post_list = Post.objects.filter(tags__name=tag,is_show=True,post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)


    def get_data(self,post_list,page,request):
        post_list = self.Pagination(post_list=post_list, page=page)
        for i in range(len(post_list)):
            md = MD()
            post_list[i].body = md.convert(post_list[i].body)
            post_list[i].toc = md.toc

        return render(request, 'blog/index.html', context={'post_list':post_list})

    # 高级分页扩展函数
    def Pagination(self, post_list, page):
        # 使用 Paginator 函数将post_list以每页per_page篇文章进行分页
        paginator = Paginator(post_list, self.per_page)
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)
        return post_list




# 博客详情页
class Detail(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)

        md = MD()
        post.body = md.convert(post.body)
        post.toc = md.toc

        # 调用 increase_views 方法，统计访问量
        post.increase_views()
        return render(request, 'blog/detail.html', context = {'post': post})
    def post(self, request):
        pass



# 归档页面
def Archives(request):
    years = Post.objects.filter(is_show=True,post_type='post').dates('created_time', 'year', order='DESC')
    post_list = Post.objects.filter(is_show=True,post_type='post').order_by('-created_time')
    return render(request, 'blog/archives.html', context={'years':years, 'post_list':post_list})


# 标签页面
def Tags(request):
    # 使用 Count 方法统计文章数，并保存到 num_posts 属性中
    tags = Tag.objects.filter(post__is_show=True,post__post_type='post').annotate(num_posts=Count('post')).filter(num_posts__gt=0).order_by('-num_posts')
    return render(request, 'blog/tags.html', context={'tags': tags})


# 关于页面
def About(request):
    post = Post.objects.filter(post_type='about').first()
    if post:
        md = MD()
        post.body = md.convert(post.body)
        post.toc = md.toc
        post.increase_views() # 调用 increase_views 方法，统计访问量
        return render(request, 'blog/about.html', context={'post': post})
    else:
        return page_not_found(request)

# 我的项目
def Project(request):
    post = Post.objects.filter(post_type='project').first()
    if post:
        md = MD()
        post.body = md.convert(post.body)
        post.toc = md.toc
        post.increase_views() # 调用 increase_views 方法，统计访问量
        return render(request, 'blog/project.html', context={'post': post})
    else:
        return page_not_found(request)

# 搜索请求
def search(request, ):
    # 搜索内容
    if request.method == 'GET':
        q = request.GET.get('q')
        post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q), is_show=True, post_type='post')

        data = {'posts':[]}
        for post in post_list:
            data['posts'].append({
                "title":post.title,
                "permalink":post.get_absolute_url(),
                "text":post.body
            },)
        return HttpResponse(json.dumps(data,ensure_ascii=False),content_type="application/json,charset=utf-8")
    else:
        pass

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}
{% get_site_configs as SITE_CONFIGS %}

{% block title %}
    {{ SITE_CONFIGS.Name }} - 关于本站
{% endblock %}

{% block l_main %}
<div class="l_main">
    <!-- 正文部分 -->
    <article id="post" class="post white-box article-type-post" itemscope="" itemprop="blogPost">

        <!-- 标题 -->
        <section class="meta">
            <div class="meta" id="header-meta">
                <h1 class="title">{{ post.title }}</h1>
                <div class="new-meta-box">
                    <div class="new-meta-item author"><a href="/blog"><i class="fas fa-user" aria-hidden="true"></i> {{ post.author }}</a></div>
                    <div class="new-meta-item date"><a class="notlink"><i class="fas fa-clock" aria-hidden="true"></i> {{ post.created_time | date:'Y-m-d H:i:s' }}</a></div>
                    <div class="new-meta-item browse busuanzi"><a class="notlink"><i class="fas fa-eye" aria-hidden="true"></i> <span id="busuanzi_value_page_pv">{{ post.views }}</span></a></div>
                </div>
                <hr>
            </div>
        </section>
        <!-- 正文 -->
        <section class="article typo">
            <div class="article-entry" itemprop="articleBody">{{ post.body | safe }}</div>

            <section class="meta" id="footer-meta">
                <hr>
                <div class="new-meta-box">
                    <div class="new-meta-item date" itemprop="dateUpdated" datetime="2017-12-25T00:00:00+08:00">
                        <a class="notlink"><i class="fas fa-pencil-alt" aria-hidden="true"></i> {{ post.modified_time | date:'Y-m-d H:i:s' }}</a>
                    </div>
                </div>
            </section>

        </section>


    </article>
    <br>

    <!-- 评论区 -->
    <article class="post white-box comments">
        <section class="article typo">
            <h4><i class="fas fa-comments fa-fw" aria-hidden="true"></i>&nbsp;评论</h4>
            <!-- Gitalk 评论 start  -->
            <!-- Link Gitalk 的支持文件  -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
            <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>

            <div id="gitalk-container"></div>
            <script type="text/javascript">
                var gitalk = new Gitalk({
                    // gitalk的主要参数
                    clientID: '{{ SITE_CONFIGS.Gitalk.clientID }}',
                    clientSecret: '{{ SITE_CONFIGS.Gitalk.clientSecret }}',
                    repo: '{{ SITE_CONFIGS.Gitalk.repo }}',
                    owner: '{{ SITE_CONFIGS.Gitalk.owner }}',
                    admin: ['{{ SITE_CONFIGS.Gitalk.admin }}'],
                    id: "{% url 'blog:About' %}",
                    distractionFreeMode: false
                });gitalk.render('gitalk-container');
            </script>
            <!-- Gitalk end -->
        </section>
    </article>

    <script>window.subData={title:"{{ post.title }}",tools:!0}</script>

</div>

{% endblock %}

templates/blog/archives.html
{% extends 'blog/base.html' %}


{% block title %}{{ SITE_CONFIGS.Name }} - 所有归档{% endblock %}

{% block l_main %}
<div class="l_main">
    <article id="archive-page" class="post article white-box">
        <section class="archive">
        {% for year in years %}
            <div class="archive-item archive-year mark"><h2>{{ year.year }}</h2><hr></div>
            {% for post in post_list %}
                {% if year.year == post.created_time.year %}
                <div class="archive-item archive-post mark">
                    <a href="{{ post.get_absolute_url }}">
                        <time>{{ post.created_time | date:'m-d' }}</time>
                        <span class="title">{{ post.title }}</span>
                    </a>
                </div>
                {% endif %}
            {% endfor %}

        {% empty %}
            找不到任何文章!
        {% endfor %}
        </section>
    </article>
</div>


{% endblock %}

templates/blog/aside.html
{% load static %}
{% load blog_tags %}
{% load blog_tags %}
{% get_site_configs as SITE_CONFIGS %}

<aside class="l_side">

    <!-- 侧边栏用户插件 -->
    <section class="author">
        <div class="content pure">
            <div class="avatar"><img class="avatar" src="{% static 'images/avatar.png' %}"></div>
            <div class="text">
                <p><span id="jinrishici-sentence">十步杀一人,千里不流行。</span></p>
                <script src="{% static 'js/jinrishici.js' %}" charset="utf-8"></script>
            </div>
            <div class="social-wrapper">
                <a href="mailto:{{ SITE_CONFIGS.Footer.Email }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external"><i class="social fas fa-envelope" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.Footer.GitHub }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-github" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.Footer.Weibo }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-weibo" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.Footer.Music }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fas fa-headphones-alt" aria-hidden="true"></i></a>
            </div>
        </div>
    </section>


    <!-- 文章目录 -->
    {% if post.toc %}
    <section class="toc-wrapper">
        <header class="pure">
            <div><i class="fas fa-list fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;文章目录</div>
            <div class="wrapper">
                <a class="s-toc rightBtn" rel="external nofollow noopener noreferrer" href="javascript:void(0)"><i class="fas fa-thumbtack fa-fw"></i></a>
            </div>
        </header>
        <div class="content pure">
            <ol class="toc">{{ post.toc | safe }}</ol>
        </div>
    </section>
    {% endif %}


    <!-- 侧边栏广告栏插件 -->
    <section class="plain">
        <header class="pure">
            <div><i class="fas fa-bullhorn fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;看这里</div>
        </header>

        <div class="content pure">
        <p> 富强、民主、文明、和谐</p>
        <p> 自由、平等、公正、法治</p>
        <p> 爱国、敬业、诚信、友善</p>

        </div>

    </section>

    <!-- 侧边栏热门标签插件 -->
    <section class="tagcloud">
        <header class="pure"><div><i class="fas fa-tags fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;热门标签</div></header>
        <div class="content pure">
            {% get_tags as tags_list %}
            {% for tag in tags_list.tags %}
            <a href="{% url 'blog:tags' tag.name %}" style="{{ tags_list.tags_style | random }}">{{ tag.name }}</a>

            {% empty %}
                <a></a>
            {% endfor %}


        </div>
    </section>

    <!-- 侧边栏友情链接插件 -->
    <section class="list">
        <header class="pure"><div><i class="fas fa-medal fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;友情链接</div></header>
        <div class="content pure">
            <ul class="entry">
                {% get_links as links %}
                {% for link in links %}
                <li><a class="flat-box waves-effect waves-block" title="{{ link.name }}" href="{{ link.url }}" target="_blank"><div class="name"><i class="fas fa-link fa-fw" aria-hidden="true"></i> &nbsp;&nbsp;{{ link.name }}</div></a></li>
                {% empty %}
                <li><a class="flat-box waves-effect waves-block" title="" href="{% url 'blog:About' %}"><div class="name"><i class="fas fa-comment-dots fa-fw" aria-hidden="true"></i> &nbsp;&nbsp;暂无友链，互换友链请留言我!</div></a></li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <!-- 侧边栏音乐插件 -->
    {% if SITE_CONFIGS.Music.enable == 'true' %}
    <section class="music">
        <header class="pure">
            <div><i class="fas fa-compact-disc fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;最近在听</div>
            <a class="rightBtn" target="_blank" rel="external nofollow noopener noreferrer" href="{{ SITE_CONFIGS.Music.home }}" title="{{ SITE_CONFIGS.Music.home }}"><i class="far fa-heart fa-fw"></i></a>
        </header>
        <div class="content pure">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.css">
            <div class="aplayer" {% if  SITE_CONFIGS.Music.autoplay == 'true' %}data-autoplay="true"{% else %}{% endif %} data-theme="#1BCDFC" data-mode="{{ SITE_CONFIGS.Music.mode }}" data-server="{{ SITE_CONFIGS.Music.server }}" data-type="{{ SITE_CONFIGS.Music.type }}" data-id="{{ SITE_CONFIGS.Music.id }}" data-volume="0.7"></div>
            <script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>
        </div>
    </section>
    {% endif %}
</aside>


templates/blog/detail.html
{% extends 'blog/base.html' %}


{% block title %}{{ SITE_CONFIGS.Name }} - {{ post.title }}{% endblock %}

{% block l_main %}
<div class="l_main">
    <!-- 正文部分 -->
    <article id="post" class="post white-box article-type-post" itemscope="" itemprop="blogPost">
        <!-- 标题 -->
        <section class="meta">
            <div class="meta" id="header-meta">
                <h1 class="title">{{ post.title }}</h1>
                <div class="new-meta-box">
                    <div class="new-meta-item author"><a href="/blog"><i class="fas fa-user" aria-hidden="true"></i> {{ post.author }}</a></div>
                    <div class="new-meta-item date"><a class="notlink"><i class="fas fa-clock" aria-hidden="true"></i> {{ post.created_time | date:'Y-m-d H:i:s' }}</a></div>
                    <div class="new-meta-item browse busuanzi"><a class="notlink"><i class="fas fa-eye" aria-hidden="true"></i> <span id="busuanzi_value_page_pv">{{ post.views }}</span></a></div>
                </div>
                <hr>
            </div>
        </section>
        <!-- 正文 -->
        <section class="article typo">
            <div class="article-entry" itemprop="articleBody">{{ post.body | safe }}</div>

            <section class="meta" id="footer-meta">
                <hr>
                <div class="new-meta-box">
                    {% for tag in post.tags.all %}
                    <div class="new-meta-item meta-tags"><a class="tag" href="{% url 'blog:tags' tag.name %}"><i class="fas fa-tag" aria-hidden="true"></i>&nbsp;{{ tag.name }}</a></div>
                    {% endfor %}
                    <div class="new-meta-item date" itemprop="dateUpdated" datetime="2017-12-25T00:00:00+08:00">
                        <a class="notlink"><i class="fas fa-pencil-alt" aria-hidden="true"></i> {{ post.modified_time | date:'Y-m-d H:i:s' }}</a>
                    </div>
                </div>
            </section>

            <div class="prev-next">
                {% if post.get_previous_by_created_time %}
                <section class="prev">
                    <span class="art-item-left">
                        <h4><a href="{{ post.get_previous_by_created_time.get_absolute_url }}" rel="prev" title="{{ post.get_previous_by_created_time.title }}"><i class="fas fa-chevron-left" aria-hidden="true"></i>&nbsp; {{ post.get_previous_by_created_time.title }}</a></h4>
                    </span>
                </section>
                {% endif %}
                {% if post.get_next_by_created_time %}
                <section class="next">
                    <span class="art-item-right" aria-hidden="true">
                        <h4><a href="{{ post.get_next_by_created_time.get_absolute_url }}" rel="prev" title="{{ post.get_next_by_created_time.title }}">{{ post.get_next_by_created_time.title }}&nbsp;<i class="fas fa-chevron-right" aria-hidden="true"></i></a></h4>
                    </span>
                </section>
                {% endif %}
            </div>
        </section>
    </article>
    <br>


    <!-- 评论区 -->
    <article class="post white-box comments">
        <section class="article typo">
            <h4><i class="fas fa-comments fa-fw" aria-hidden="true"></i>&nbsp;评论</h4>

            <!-- Gitalk 评论 start  -->
            <!-- Link Gitalk 的支持文件  -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
            <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>

            <div id="gitalk-container"></div>
            <script type="text/javascript">
                var gitalk = new Gitalk({
                    // gitalk的主要参数
                    clientID: '{{ SITE_CONFIGS.Gitalk.clientID }}',
                    clientSecret: '{{ SITE_CONFIGS.Gitalk.clientSecret }}',
                    repo: '{{ SITE_CONFIGS.Gitalk.repo }}',
                    owner: '{{ SITE_CONFIGS.Gitalk.owner }}',
                    admin: ['{{ SITE_CONFIGS.Gitalk.admin }}'],
                    id: "{{ post.get_absolute_url }}",
                    distractionFreeMode: false
                });gitalk.render('gitalk-container');
            </script>
            <!-- Gitalk end -->

        </section>
    </article>

    <script>window.subData={title:"{{ post.title }}",tools:!0}</script>

</div>
{% endblock %}

templates/blog/header.html
<div id="loading-bar-wrapper" style="display: none;">
    <div id="loading-bar" class="pure" style="width: 100%;"></div>
</div>
<script>setLoadingBarProgress(20)</script>
<header class="l_header pure">
    <div class="wrapper">
        <div class="nav-main container container--flex">
            <a class="logo flat-box waves-effect waves-block" href="{% url 'blog:Index' %}">{{ SITE_CONFIGS.Name }}'s Blog</a>
            <div class="menu">
                <ul class="h-list">
                    <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                    <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                    <li><a id="blogtags" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tags' %}"><i class="fas fa-tags fa-fw"></i>&nbsp;标签</a></li>
                    <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                    <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                    <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
                </ul>
            </div>
            <div class="m_search">
                <form name="searchform" class="form u-search-form">
                    <input type="text" class="input u-search-input" placeholder="搜索">
                    <span class="icon"><i class="fas fa-search fa-fw"></i></span>
                </form>
            </div>
            <ul class="switcher h-list">
                <li class="s-search"><a class="fas fa-search fa-fw" href="javascript:void(0)"></a></li>
                <li class="s-menu"><a class="fas fa-bars fa-fw" href="javascript:void(0)"></a></li>
            </ul>
        </div>

        <div class="nav-sub container container--flex">
            <a class="logo flat-box waves-effect waves-block"></a>
            <ul class="switcher h-list">
                <li class="s-comment"><a class="flat-btn fas fa-comments fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
                <li class="s-toc"><a class="flat-btn fas fa-list fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
            </ul>
        </div>
    </div>
</header>
<aside class="menu-phone">
    <header>
        <nav class="menu">
            <ul>
                <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                <li><a id="blogtags" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tags' %}"><i class="fas fa-tags fa-fw"></i>&nbsp;标签</a></li>
                <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
            </ul>
        </nav>
    </header>
</aside>

templates/blog/tags.html
{% extends 'blog/base.html' %}


{% block title %}Attila-Zang - 所有标签{% endblock %}

{% block l_main %}
<div class="l_main">
    <section class="post-list">
        <div class="post-wrapper">
            <article id="archive-page" class="post article white-box">
                <section class="archive">
                    <div class="archive-item archive-year mark"><h2>所有标签</h2><hr></div>
                    <div class="archive-item archive-post mark">
                        {% for tag in tags %}
                        <a href="{% url 'blog:tags' tag.name %}"><time><i class="fas fa-tag fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;{{ tag.name }}</time> <span class="title">({{ tag.num_posts }}) </span></a>

                        {% endfor %}
                    </div>
                    <br>
                </section>
            </article>
        </div>
    </section>
</div>


{% endblock %}